title:             Powerberry
email:             powerberry1@naver.com
description:       코딩 초보의 코딩 공부 블로그
author:            powerberry
baseurl:           
url:               "http://powerberry1.github.io"

# Social Profiles
blog_username:     powerberry1
github_username:   powerberry1
sns_username:      powerberry93

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
